Importando Bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_ag_econ = pd.read_csv('AgentesEconomicosRegulares.csv', encoding='latin1', sep=';')
df_ag_econ = df_ag_econ[['REGISTRO_ANCINE',	'DATA_REGISTRO', 'RAZAO_SOCIAL', 'MUNICIPIO', 'CD_MUNICIPIO_IBGE', 'UF', 'CLASSIFICACAO_AGENTE_ECONOMICO']]
df_ag_econ

,REGISTRO_ANCINE,DATA_REGISTRO,RAZAO_SOCIAL,MUNICIPIO,CD_MUNICIPIO_IBGE,UF,CLASSIFICACAO_AGENTE_ECONOMICO
0,3132,01/02/2005,CINEMAS ALVORADA DIVERSÕES LTDA,RIBEIRÃO PRETO,3543402.0,SP,Brasileiro de capital nacional nos termos do a...
1,5387,01/02/2006,SANDRA HELENA SILVINO PARENTE - ME,FORTALEZA,2304400.0,CE,Brasileiro independente
2,11893,01/02/2007,CAVIDEO PRODUCOES COMERCIO E LOCACAO DE FILMES...,RIO DE JANEIRO,3304557.0,RJ,Brasileiro independente
3,18260,01/02/2011,COMERCIAL TALKING LTDA-ME,BARRETOS,3505500.0,SP,Brasileiro independente
4,18261,01/02/2011,CENAUM PRODUÇÕES LTDA.,PORTO ALEGRE,4314902.0,RS,Brasileiro independente
...,...,...,...,...,...,...,...
14796,52264,31/10/2022,SISTEMA O NORTE DE COMUNICAÇÃO LTDA,ARAGUAÍNA,1702109.0,TO,Brasileiro de capital nacional nos termos do a...
14797,52263,31/10/2022,DARLY INACIO ALVES JUNIOR ALUGUEL,PORTO ALEGRE,4314902.0,RS,Brasileiro independente
14798,52266,31/10/2022,FREYA PRODUÇÕES AUDIOVISUAIS EIRELI,SÃO PAULO,3550308.0,SP,Brasileiro independente
14799,28605,31/12/2014,NUKEARTS SERVIÇOS GRAFICOS LTDA - ME,JOINVILLE,4209102.0,SC,Brasileiro independente
14800,31758,31/12/2015,HILDEBRANDO MAURICIO DA C MACEDO FILHO ­ ME,FORTALEZA,2304400.0,CE,Brasileiro independente

In [3]:
df_ag_econ['DATA_REGISTRO'] = df_ag_econ['DATA_REGISTRO'].astype(str).str.strip()
df_ag_econ['DATA_REGISTRO'] = pd.to_datetime(df_ag_econ['DATA_REGISTRO'], format='mixed', dayfirst=True)
df_ag_econ.head(30)

,REGISTRO_ANCINE,DATA_REGISTRO,RAZAO_SOCIAL,MUNICIPIO,CD_MUNICIPIO_IBGE,UF,CLASSIFICACAO_AGENTE_ECONOMICO
0,3132,2005-02-01,CINEMAS ALVORADA DIVERSÕES LTDA,RIBEIRÃO PRETO,3543402.0,SP,Brasileiro de capital nacional nos termos do a...
1,5387,2006-02-01,SANDRA HELENA SILVINO PARENTE - ME,FORTALEZA,2304400.0,CE,Brasileiro independente
2,11893,2007-02-01,CAVIDEO PRODUCOES COMERCIO E LOCACAO DE FILMES...,RIO DE JANEIRO,3304557.0,RJ,Brasileiro independente
3,18260,2011-02-01,COMERCIAL TALKING LTDA-ME,BARRETOS,3505500.0,SP,Brasileiro independente
4,18261,2011-02-01,CENAUM PRODUÇÕES LTDA.,PORTO ALEGRE,4314902.0,RS,Brasileiro independente
5,20776,2012-02-01,PAULO TARSO MACHADO SARAIVA,BAGÉ,4301602.0,RS,Brasileiro independente
6,20775,2012-02-01,SUSAN PEREIRA DA SILVA,SALVADOR,2927408.0,BA,Brasileiro independente
7,23180,2013-02-01,OSS PRODUÇÕES LTDA ME,SÃO PAULO,3550308.0,SP,Brasileiro independente
8,31968,2016-02-01,HELENA PRODUCOES ARTISTICAS LTDA,SÃO PAULO,3550308.0,SP,Brasileiro independente
9,35292,2017-02-01,4 BOCAS - FILMES E SERVIÇOS AUDIOVISUAIS LTDA,BRASÍLIA,5300108.0,DF,Brasileiro independente
10,35296,2017-02-01,CONTEÚDO FILMES PRODUÇÕES AUDIOVISUAIS,RIO DE JANEIRO,3304557.0,RJ,Brasileiro independente
11,35298,2017-02-01,KOCHE FILMES LTDA,BALNEÁRIO CAMBORIÚ,4202008.0,SC,Brasileiro independente
12,42131,2019-02-01,MEGABIT PROVEDOR DE INTERNET LTDA,OSASCO,3534401.0,SP,Brasileiro de capital nacional nos termos do a...
13,42132,2019-02-01,ANDREY CASSARO - ME,CAMPINAS,3509502.0,SP,Brasileiro independente
14,42133,2019-02-01,CWA LUMINARIS ASSESSORIA EMPRESARIAL LTDA.,SÃO PAULO,3550308.0,SP,Brasileiro independente
15,47653,2021-02-01,ART MAKER PUBLICIDADE LTDA,SOROCABA,3552205.0,SP,Brasileiro independente
16,47652,2021-02-01,ATROM PRODUCOES E CONSULTORIA LTDA,VITÓRIA,3205309.0,ES,Brasileiro independente
17,50405,2022-02-01,URBAN FILMS EIRELI,RIO DE JANEIRO,3304557.0,RJ,Brasileiro independente
18,50403,2022-02-01,DANIEL VILACA LEITE,ARAXÁ,3104007.0,MG,Brasileiro independente
19,50412,2022-02-01,ROKE PRODUÇÕES ARTÍSTICAS LTDA,GOIÂNIA,5208707.0,GO,Brasileiro independente
20,50410,2022-02-01,INSANNA PRODUCOES LTDA - ME,SÃO PAULO,3550308.0,SP,Brasileiro independente
21,50409,2022-02-01,CENA RARA FILMES E PRODUCOES LTDA,SALVADOR,2927408.0,BA,Brasileiro independente
22,50406,2022-02-01,"BR CONSULTORIA, PRODUCAO E SERVICOS EM PROJETO...",BRASÍLIA,5300108.0,DF,Brasileiro independente
23,50408,2022-02-01,TERRA UPAON AÇU FILMES LTDA,SÃO LUÍS,2111300.0,MA,Brasileiro independente
24,50411,2022-02-01,YOU CAST PARTICIPAÇÕES E ADMINISTRAÇÃO DE BENS...,SÃO PAULO,3550308.0,SP,Brasileiro de capital nacional nos termos do a...
25,52745,2023-02-01,FABIO ANDRE DE OLIVEIRA MALVEIRA,MANAUS,1302603.0,AM,Brasileiro independente
26,52738,2023-02-01,L A LOBATO LTDA,MACAPÁ,1600303.0,AP,Brasileiro independente
27,52743,2023-02-01,49.392.003 CAMILA MARQUES DE CARVALHO KHOURI,VITÓRIA DA CONQUISTA,2933307.0,BA,Brasileiro independente
28,52739,2023-02-01,49.405.221 FREDERICO DO SACRAMENTO JANUARIO,VITÓRIA,3205309.0,ES,Brasileiro de capital nacional nos termos do a...
29,52740,2023-02-01,CN FILMES E PRODUÇOES ARTÍSTICAS LTDA,RIO DE JANEIRO,3304557.0,RJ,Brasileiro independente

In [4]:
df_ag_econ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14801 entries, 0 to 14800
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   REGISTRO_ANCINE                 14801 non-null  int64
 1   DATA_REGISTRO                   14801 non-null  datetime64[ns]
 2   RAZAO_SOCIAL                    14801 non-null  object
 3   MUNICIPIO                       14801 non-null  object
 4   CD_MUNICIPIO_IBGE               14792 non-null  float64
 5   UF                              14801 non-null  object
 6   CLASSIFICACAO_AGENTE_ECONOMICO  14801 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 809.6+ KB

In [5]:
df_ag_econ['CD_MUNICIPIO_IBGE'].isnull().value_counts()

CD_MUNICIPIO_IBGE
False    14792
True         9
Name: count, dtype: int64

In [6]:
null_values = []
default_value = 3550308.0

for index, row in df_ag_econ.iterrows():
    if pd.isnull(row['CD_MUNICIPIO_IBGE']):
        row['CD_MUNICIPIO_IBGE'] = default_value
        null_values.append(index)

df_ag_econ['CD_MUNICIPIO_IBGE'].fillna(default_value, inplace=True)

In [7]:
df_ag_econ.to_csv('agentes_br.csv', index=False)

In [8]:
df_ag_econ['ANO'] = df_ag_econ['DATA_REGISTRO'].dt.year
df_ag_econ['ANO'].value_counts()

ANO
2021    1837
2018    1742
2022    1649
2019    1622
2020    1603
2013     624
2015     586
2014     584
2023     457
2016     453
2012     399
2011     389
2017     379
2005     370
2010     367
2003     289
2004     286
2008     286
2009     281
2006     211
2002     196
2007     191
Name: count, dtype: int64