In [1]:
import pandas as pd
import numpy as np

In [2]:
df_salas_exib = pd.read_csv('SalasDeExibicaoEComplexos.csv', encoding='latin1', sep=';')
df_salas_exib = df_salas_exib[['NOME_SALA', 'SITUACAO_SALA',
       'ASSENTOS_SALA', 'NOME_COMPLEXO',
       'MUNICIPIO_COMPLEXO', 'UF_COMPLEXO',
       'COMPLEXO_ITINERANTE', 'OPERACAO_USUAL', 'SITUACAO_EXIBIDOR',
       'GRUPO_EXIBIDOR']]

In [3]:
df_salas_exib

,NOME_SALA,SITUACAO_SALA,ASSENTOS_SALA,NOME_COMPLEXO,MUNICIPIO_COMPLEXO,UF_COMPLEXO,COMPLEXO_ITINERANTE,OPERACAO_USUAL,SITUACAO_EXIBIDOR,GRUPO_EXIBIDOR
0,CINE SEGALL,EM FUNCIONAMENTO,80.0,CINE SEGALL,SÃO PAULO,SP,NÃO,COMERCIAL,REGULAR,NAO PERTENCE A NENHUM GRUPO EXIBIDOR
1,CINESERCLA NILÓPOLIS SQUARE SALA 01,EM FUNCIONAMENTO,171.0,CINESERCLA NILÓPOLIS,NILÓPOLIS,RJ,NÃO,COMERCIAL,REGULAR,CINESERCLA
2,CINESERCLA NILÓPOLIS SQUARE SALA 02,EM FUNCIONAMENTO,106.0,CINESERCLA NILÓPOLIS,NILÓPOLIS,RJ,NÃO,COMERCIAL,REGULAR,CINESERCLA
3,CINESERCLA NILÓPOLIS SQUARE SALA 03,EM FUNCIONAMENTO,130.0,CINESERCLA NILÓPOLIS,NILÓPOLIS,RJ,NÃO,COMERCIAL,REGULAR,CINESERCLA
4,CINESERCLA PÁTIO ITAGUAÍ SALA 01,EM FUNCIONAMENTO,114.0,CINESERCLA PÁTIO MIX ITAGUAI,ITAGUAÍ,RJ,NÃO,COMERCIAL,REGULAR,CINESERCLA
...,...,...,...,...,...,...,...,...,...,...
3691,CINE CARIOCA NOVA BRASÍLIA,EM FUNCIONAMENTO,91.0,CINE CARIOCA NOVA BRASÍLIA,RIO DE JANEIRO,RJ,NÃO,COMERCIAL,REGULAR,NAO PERTENCE A NENHUM GRUPO EXIBIDOR
3692,WEST CINE SALA 01,EM FUNCIONAMENTO,200.0,WEST CINE,CASCAVEL,PR,NÃO,COMERCIAL,REGULAR,NAO PERTENCE A NENHUM GRUPO EXIBIDOR
3693,WEST CINE SALA 02,EM FUNCIONAMENTO,180.0,WEST CINE,CASCAVEL,PR,NÃO,COMERCIAL,REGULAR,NAO PERTENCE A NENHUM GRUPO EXIBIDOR
3694,WEST CINE SALA 03,EM FUNCIONAMENTO,191.0,WEST CINE,CASCAVEL,PR,NÃO,COMERCIAL,REGULAR,NAO PERTENCE A NENHUM GRUPO EXIBIDOR
3695,CINEMEC TAQUARITINGA - CINE MIZIARA,EM FUNCIONAMENTO,150.0,CINEMEC CINE MIZIARA,TAQUARITINGA,SP,NÃO,COMERCIAL,IRREGULAR,NAO PERTENCE A NENHUM GRUPO EXIBIDOR

In [4]:
df_salas_exib.isnull().sum()

NOME_SALA              21
SITUACAO_SALA          21
ASSENTOS_SALA          21
NOME_COMPLEXO           0
MUNICIPIO_COMPLEXO     21
UF_COMPLEXO            21
COMPLEXO_ITINERANTE     0
OPERACAO_USUAL          0
SITUACAO_EXIBIDOR       0
GRUPO_EXIBIDOR          0
dtype: int64

In [5]:
for index, row in df_salas_exib.iterrows():
    if pd.isnull(row['ASSENTOS_SALA']):
        df_salas_exib.at[index, 'ASSENTOS_SALA'] = 0


for index, row in df_salas_exib.iterrows():
    if pd.isnull(row['NOME_SALA']):
        df_salas_exib.at[index, 'NOME_SALA'] = 'SEM NOME'


for index, row in df_salas_exib.iterrows():
    if pd.isnull(row['MUNICIPIO_COMPLEXO']):
        df_salas_exib.at[index, 'MUNICIPIO_COMPLEXO'] = 'SEM UF'


for index, row in df_salas_exib.iterrows():
    if pd.isnull(row['UF_COMPLEXO']):
        df_salas_exib.at[index, 'UF_COMPLEXO'] = 'SEM UF'


for index, row in df_salas_exib.iterrows():
    if pd.isnull(row['SITUACAO_SALA']):
        df_salas_exib.at[index, 'SITUACAO_SALA'] = 'SEM STATUS'

In [8]:
df_salas_exib['ASSENTOS_SALA'] = df_salas_exib['ASSENTOS_SALA'].astype(int)

In [10]:
df_salas_exib.to_csv('salas_exibi.csv')